name: Deploy to EC2 (Netflix App)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Navigate to home
            cd /home/ec2-user

            # Remove temp folder if it exists
            rm -rf temp-repo

            # Clone the repo
            git clone https://github.com/bhargavirengarajan21/netflix-portfolio.git app

            # Go to app and deploy
            cd app
            docker-compose down || true
            docker-compose up -d --build
            sudo systemctl reload nginx
